In [14]:

# Imports
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", 100)
data_path = Path("nashville_housing_data.csv")
assert data_path.exists(), "Place 'nashville_housing_data.csv' in the same folder as this notebook."

## 1) Load the dataset & basic profile

In [15]:

# 1. Load the dataset
df = pd.read_csv(data_path)

# Display the first 5 rows
df.head()

,Unnamed: 0.1,Unnamed: 0,Parcel ID,Land Use,Property Address,Suite/ Condo #,Property City,Sale Date,Sale Price,Legal Reference,Sold As Vacant,Multiple Parcels Involved in Sale,Owner Name,Address,City,State,Acreage,Tax District,Neighborhood,image,Land Value,Building Value,Total Value,Finished Area,Foundation Type,Year Built,Exterior Wall,Grade,Bedrooms,Full Bath,Half Bath
0,0,0,105 03 0D 008.00,RESIDENTIAL CONDO,1208 3RD AVE S,8,NASHVILLE,2013-01-24,132000,20130128-0008725,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,105 11 0 080.00,SINGLE FAMILY,1802 STEWART PL,NaN,NASHVILLE,2013-01-11,191500,20130118-0006337,No,No,"STINSON, LAURA M.",1802 STEWART PL,NASHVILLE,TN,0.17,URBAN SERVICES DISTRICT,3127.0,\114000\910001.JPG,32000.0,134400.0,168300.0,1149.00000,PT BSMT,1941.0,BRICK,C,2.0,1.0,0.0
2,2,2,118 03 0 130.00,SINGLE FAMILY,2761 ROSEDALE PL,NaN,NASHVILLE,2013-01-18,202000,20130124-0008033,No,No,"NUNES, JARED R.",2761 ROSEDALE PL,NASHVILLE,TN,0.11,CITY OF BERRY HILL,9126.0,\131000\191001.JPG,34000.0,157800.0,191800.0,2090.82495,SLAB,2000.0,BRICK/FRAME,C,3.0,2.0,1.0
3,3,3,119 01 0 479.00,SINGLE FAMILY,224 PEACHTREE ST,NaN,NASHVILLE,2013-01-18,32000,20130128-0008863,No,No,"WHITFORD, KAREN",224 PEACHTREE ST,NASHVILLE,TN,0.17,URBAN SERVICES DISTRICT,3130.0,\133000\721001.JPG,25000.0,243700.0,268700.0,2145.60001,FULL BSMT,1948.0,BRICK/FRAME,B,4.0,2.0,0.0
4,4,4,119 05 0 186.00,SINGLE FAMILY,316 LUTIE ST,NaN,NASHVILLE,2013-01-23,102000,20130131-0009929,No,No,"HENDERSON, JAMES P. & LYNN P.",316 LUTIE ST,NASHVILLE,TN,0.34,URBAN SERVICES DISTRICT,3130.0,\134000\474001.JPG,25000.0,138100.0,164800.0,1969.00000,CRAWL,1910.0,FRAME,C,2.0,1.0,0.0

In [16]:

# Use .info() to inspect dtypes and missingness
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56636 entries, 0 to 56635
Data columns (total 31 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Unnamed: 0.1                       56636 non-null  int64
 1   Unnamed: 0                         56636 non-null  int64
 2   Parcel ID                          56636 non-null  object
 3   Land Use                           56636 non-null  object
 4   Property Address                   56477 non-null  object
 5   Suite/ Condo   #                   6109 non-null   object
 6   Property City                      56477 non-null  object
 7   Sale Date                          56636 non-null  object
 8   Sale Price                         56636 non-null  int64
 9   Legal Reference                    56636 non-null  object
 10  Sold As Vacant                     56636 non-null  object
 11  Multiple Parcels Involved in Sale  56636 non-null  object
 12  Owner Name                         25261 non-null  object
 13  Address                            26017 non-null  object
 14  City                               26017 non-null  object
 15  State                              26017 non-null  object
 16  Acreage                            26017 non-null  float64
 17  Tax District                       26017 non-null  object
 18  Neighborhood                       26017 non-null  float64
 19  image                              25335 non-null  object
 20  Land Value                         26017 non-null  float64
 21  Building Value                     26017 non-null  float64
 22  Total Value                        26017 non-null  float64
 23  Finished Area                      24166 non-null  float64
 24  Foundation Type                    24164 non-null  object
 25  Year Built                         24165 non-null  float64
 26  Exterior Wall                      24165 non-null  object
 27  Grade                              24165 non-null  object
 28  Bedrooms                           24159 non-null  float64
 29  Full Bath                          24277 non-null  float64
 30  Half Bath                          24146 non-null  float64
dtypes: float64(10), int64(3), object(18)
memory usage: 13.4+ MB

In [17]:

# Numeric summary
df.describe(include=[np.number]).T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0.1,56636.0,28317.500000,16349.549260,0.00,14158.75,28317.50,42476.25,56635.00
Unnamed: 0,56636.0,28317.500000,16349.549260,0.00,14158.75,28317.50,42476.25,56635.00
Sale Price,56636.0,327211.128911,928742.546637,50.00,135000.00,205450.00,329000.00,54278060.00
Acreage,26017.0,0.498903,1.570396,0.01,0.18,0.27,0.45,160.06
Neighborhood,26017.0,4356.215782,2170.348270,107.00,3126.00,3929.00,6228.00,9530.00
Land Value,26017.0,69072.665027,106040.533131,100.00,21000.00,28800.00,60000.00,2772000.00
Building Value,26017.0,160802.458969,206804.058426,0.00,75900.00,111400.00,180700.00,12971800.00
Total Value,26017.0,232397.094246,281070.266610,100.00,102800.00,148500.00,268500.00,13940400.00
Finished Area,24166.0,1926.954345,1687.017313,0.00,1239.00,1632.00,2212.00,197988.00
Year Built,24165.0,1963.749224,26.546141,1799.00,1948.00,1960.00,1983.00,2017.00
Bedrooms,24159.0,3.090029,0.852942,0.00,3.00,3.00,3.00,11.00
Full Bath,24277.0,1.886106,0.961572,0.00,1.00,2.00,2.00,10.00
Half Bath,24146.0,0.283981,0.487905,0.00,0.00,0.00,1.00,3.00

## 2) Standardize headings to lower_snake_case

In [18]:

# Helper to convert column names to snake_case
import re

def to_snake(name: str) -> str:
    # Strip, lower, replace non-alphanumerics with underscores, collapse repeats
    s = name.strip().lower()
    s = re.sub(r"[^0-9a-z]+", "_", s)
    s = re.sub(r"_+", "_", s)
    return s.strip("_")

df.columns = [to_snake(c) for c in df.columns]
df.columns

Index(['unnamed_0_1', 'unnamed_0', 'parcel_id', 'land_use', 'property_address',
       'suite_condo', 'property_city', 'sale_date', 'sale_price',
       'legal_reference', 'sold_as_vacant',
       'multiple_parcels_involved_in_sale', 'owner_name', 'address', 'city',
       'state', 'acreage', 'tax_district', 'neighborhood', 'image',
       'land_value', 'building_value', 'total_value', 'finished_area',
       'foundation_type', 'year_built', 'exterior_wall', 'grade', 'bedrooms',
       'full_bath', 'half_bath'],
      dtype='object')

## 3) Eliminate unneeded columns (`unnamed_0.1`, `unnamed_0`)

In [19]:

drop_cols = [c for c in ["unnamed_0_1", "unnamed_0.1", "unnamed_0"] if c in df.columns]
# Note: If the original file had 'Unnamed: 0.1', after snake_case it may become 'unnamed_0_1'
df = df.drop(columns=drop_cols, errors="ignore")
drop_cols

['unnamed_0_1', 'unnamed_0']


## 4) Handle missing values
- Drop rows where `sale_price` is missing  
- Fill missing `bedrooms` with the median

In [20]:

# Ensure sale_price is numeric before checking missingness
if "sale_price" in df.columns:
    df["sale_price"] = pd.to_numeric(df["sale_price"], errors="coerce")
else:
    raise KeyError("Expected column 'sale_price' not found after renaming.")

before_rows = len(df)
df = df.dropna(subset=["sale_price"])
after_rows = len(df)
dropped_rows = before_rows - after_rows

dropped_rows, after_rows

(0, 56636)

In [21]:

# Fill missing bedrooms with median (coerce to numeric first)
if "bedrooms" in df.columns:
    df["bedrooms"] = pd.to_numeric(df["bedrooms"], errors="coerce")
    median_bed = df["bedrooms"].median()
    df["bedrooms"] = df["bedrooms"].fillna(median_bed)
else:
    print("Warning: 'bedrooms' column not found; skipping median imputation.")
median_bed if "median_bed" in locals() else None

3.0

## 5) Convert `sale_date` to datetime

In [22]:

# Convert sale_date to datetime
if "sale_date" in df.columns:
    df["sale_date"] = pd.to_datetime(df["sale_date"], errors="coerce")
    df["sale_year"] = df["sale_date"].dt.year  # convenience feature
    df["sale_month"] = df["sale_date"].dt.month
else:
    print("Warning: 'sale_date' column not found; skipping datetime conversion.")
df.dtypes

parcel_id                                    object
land_use                                     object
property_address                             object
suite_condo                                  object
property_city                                object
sale_date                            datetime64[ns]
sale_price                                    int64
legal_reference                              object
sold_as_vacant                               object
multiple_parcels_involved_in_sale            object
owner_name                                   object
address                                      object
city                                         object
state                                        object
acreage                                     float64
tax_district                                 object
neighborhood                                float64
image                                        object
land_value                                  float64
building_value                              float64
total_value                                 float64
finished_area                               float64
foundation_type                              object
year_built                                  float64
exterior_wall                                object
grade                                        object
bedrooms                                    float64
full_bath                                   float64
half_bath                                   float64
sale_year                                     int32
sale_month                                    int32
dtype: object


## 6) Standardize `sold_as_vacant` to only **Yes** / **No**
Accept common variants like Y/Yes/True/1 and N/No/False/0.

In [23]:

def normalize_yes_no(x):
    if pd.isna(x):
        return x
    s = str(x).strip().casefold()
    yes_set = {"y", "yes", "true", "1"}
    no_set  = {"n", "no", "false", "0"}
    if s in yes_set:
        return "Yes"
    if s in no_set:
        return "No"
    # If unknown value, leave as-is or set to NaN; here we leave as-is to avoid data loss
    return "Yes" if s.startswith("y") else ("No" if s.startswith("n") else np.nan)

if "sold_as_vacant" in df.columns:
    df["sold_as_vacant"] = df["sold_as_vacant"].apply(normalize_yes_no)
    # If any remaining NaN due to odd values, choose a default if needed; here we leave NaN.
else:
    print("Warning: 'sold_as_vacant' column not found; skipping standardization.")

df["sold_as_vacant"].value_counts(dropna=False) if "sold_as_vacant" in df.columns else "sold_as_vacant not present"

sold_as_vacant
No     51741
Yes     4895
Name: count, dtype: int64

## 7) Save the cleaned dataset

In [24]:

out_path = Path("nashville_housing_cleaned.csv")
df.to_csv(out_path, index=False)
out_path, df.shape

(WindowsPath('nashville_housing_cleaned.csv'), (56636, 31))

## Final checks

In [25]:

# Confirm only 'Yes'/'No' (or NaN) in sold_as_vacant
if "sold_as_vacant" in df.columns:
    print(df["sold_as_vacant"].value_counts(dropna=False))

# Preview cleaned head
df.head()

sold_as_vacant
No     51741
Yes     4895
Name: count, dtype: int64

,parcel_id,land_use,property_address,suite_condo,property_city,sale_date,sale_price,legal_reference,sold_as_vacant,multiple_parcels_involved_in_sale,owner_name,address,city,state,acreage,tax_district,neighborhood,image,land_value,building_value,total_value,finished_area,foundation_type,year_built,exterior_wall,grade,bedrooms,full_bath,half_bath,sale_year,sale_month
0,105 03 0D 008.00,RESIDENTIAL CONDO,1208 3RD AVE S,8,NASHVILLE,2013-01-24,132000,20130128-0008725,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,2013,1
1,105 11 0 080.00,SINGLE FAMILY,1802 STEWART PL,NaN,NASHVILLE,2013-01-11,191500,20130118-0006337,No,No,"STINSON, LAURA M.",1802 STEWART PL,NASHVILLE,TN,0.17,URBAN SERVICES DISTRICT,3127.0,\114000\910001.JPG,32000.0,134400.0,168300.0,1149.00000,PT BSMT,1941.0,BRICK,C,2.0,1.0,0.0,2013,1
2,118 03 0 130.00,SINGLE FAMILY,2761 ROSEDALE PL,NaN,NASHVILLE,2013-01-18,202000,20130124-0008033,No,No,"NUNES, JARED R.",2761 ROSEDALE PL,NASHVILLE,TN,0.11,CITY OF BERRY HILL,9126.0,\131000\191001.JPG,34000.0,157800.0,191800.0,2090.82495,SLAB,2000.0,BRICK/FRAME,C,3.0,2.0,1.0,2013,1
3,119 01 0 479.00,SINGLE FAMILY,224 PEACHTREE ST,NaN,NASHVILLE,2013-01-18,32000,20130128-0008863,No,No,"WHITFORD, KAREN",224 PEACHTREE ST,NASHVILLE,TN,0.17,URBAN SERVICES DISTRICT,3130.0,\133000\721001.JPG,25000.0,243700.0,268700.0,2145.60001,FULL BSMT,1948.0,BRICK/FRAME,B,4.0,2.0,0.0,2013,1
4,119 05 0 186.00,SINGLE FAMILY,316 LUTIE ST,NaN,NASHVILLE,2013-01-23,102000,20130131-0009929,No,No,"HENDERSON, JAMES P. & LYNN P.",316 LUTIE ST,NASHVILLE,TN,0.34,URBAN SERVICES DISTRICT,3130.0,\134000\474001.JPG,25000.0,138100.0,164800.0,1969.00000,CRAWL,1910.0,FRAME,C,2.0,1.0,0.0,2013,1